# GoConsole Lite Android 12-16 — Nokia T10
TARGET_ARCH := arm64
TARGET_ARCH_VARIANT := armv8-a
TARGET_CPU_ABI := arm64-v8a
TARGET_BOARD_PLATFORM := unisoc_t606
TARGET_KERNEL_SOURCE := kernel/nokia/t10
BOARD_KERNEL_BASE := 0x00000000
BOARD_KERNEL_PAGESIZE := 2048
TARGET_USES_64_BIT_BINDER := true
# GoConsole touch
TARGET_USES_TOUCHSCREEN := true
